### ISSUE TITLE
Death and Respawn System

### ISSUE THREAD

**Issue by sc0ttr0berts0n** [sc0ttr0berts0n/shitty-rockets#13]
## Todo
- [ ] Rework Spawn method to only spawn at discrete spots. (formula below)
- [ ] Kill Rocket if it falls below the floor
- [ ] Respawn Dead Rocket
- [ ] Track Lives (5)

### Respawn Formula
`spawnNode.x = (platform.width / rockets.length) - (platform.width / rockets.length / 2)`
offset the next one by `(platform.width / rockets.length)`

This should distribute the nodes like this given `n` rockets.
`[      x     ]`
`[    x    x    ]`
`[   x   x   x   ]`
`[  x  x  x  x  x  x  ]`

**Comment by sc0ttr0berts0n** [comment]
inital work is done, kinds to work out
